[package]
name = "owner/soccer"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.2"
Component = "sleitnick/component@2.4.2"
Loader = "sleitnick/loader@1.0.2"
Option = "sleitnick/option@1.0.3"
Signal = "sleitnick/signal@1.1.0"
TaskQueue = "sleitnick/task-queue@0.1.0"
Trove = "sleitnick/trove@0.2.0"
Promise = "evaera/promise@4.0.0-rc.2"
